"""upd  

Revision ID: 1cbbfc9dd11e
Revises: b1f56269e826
Create Date: 2025-10-25 09:47:45.183041

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cbbfc9dd11e'
down_revision: str | Sequence[str] | None = 'b1f56269e826'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_task',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('check_uid', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('bound_to_agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bound_to_agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['check_uid'], ['check.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_task')
    op.drop_table('resource')
    op.drop_table('check')
    # ### end Alembic commands ###
