"""upd  

Revision ID: b1f56269e826
Revises: 16ec54d2a72b
Create Date: 2025-10-25 08:21:30.852486

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1f56269e826'
down_revision: str | Sequence[str] | None = '16ec54d2a72b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_keypair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('public_key_openssh', sa.String(), nullable=False),
    sa.Column('private_key_pem', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent', sa.Column('rhost', sa.String(), nullable=False))
    op.add_column('agent', sa.Column('rport', sa.Integer(), nullable=False))
    op.add_column('agent', sa.Column('suspended_since', sa.DateTime(), nullable=True))
    op.add_column('agent', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('agent', sa.Column('keypair_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('agent_ssh_public_key_key'), 'agent', type_='unique')
    op.create_foreign_key(None, 'agent', 'agent_keypair', ['keypair_id'], ['id'])
    op.drop_column('agent', 'ssh_public_key')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.add_column('agent', sa.Column('ssh_public_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'agent', type_='foreignkey')
    op.create_unique_constraint(op.f('agent_ssh_public_key_key'), 'agent', ['ssh_public_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('agent', 'keypair_id')
    op.drop_column('agent', 'created_at')
    op.drop_column('agent', 'suspended_since')
    op.drop_column('agent', 'rport')
    op.drop_column('agent', 'rhost')
    op.drop_table('agent_keypair')
    # ### end Alembic commands ###
